name: Scripts validation

on:
  push:
    branches:
      - main
      - feature/*
      - dependabot/*
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test shell scripts
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate with shellcheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: "./functions"

  sonar:
    uses: kpatryk/workflows/.github/workflows/sonar.yml@v0.1.0
    with:
      os: ubuntu-latest
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
