name: Shellcheck Validation

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*
    paths-ignore:
      - "**/*.md"

jobs:
  script-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Executability of Shell Scripts
        run: |
          for file in $(find functions -type f -name "*.sh")
          do
            if [ -x "$file" ]; then
              echo "Error: $file is executable" && exit 1
            fi
          done

  shellcheck:
    needs: script-validation
    uses: kpatryk/workflows/.github/workflows/shellcheck.yml@v0.2.0
    with:
      os: ubuntu-latest
      scandir: functions/
