name: Shellcheck Validation

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*
    paths-ignore:
      - "**/*.md"

jobs:
  shellcheck:
    uses: kpatryk/workflows/.github/workflows/shellcheck.yml@v0.2.0
    with:
      os: ubuntu-latest
      scandir: functions/
