name: Shellcheck Validation

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - feature/*
    paths-ignore:
    - "**/*.md"

jobs:
  script-validation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check whether shell functions are executable
      run: |
        for file in $(find functions -type f -name "*.sh")
        do
          if [ -x "$file" ]; then
            echo "Error: $file is executable" && exit 1
          fi
        done

    - name: Install Bats
      run: |
        sudo apt-get update
        sudo apt-get install -y bats

    - name: Run Bats tests
      run: bats -r tests/

  shellcheck:
    needs: script-validation
    uses: kpatryk/workflows/.github/workflows/shellcheck.yml@v0.2.1
    with:
      os: ubuntu-latest
      scandir: functions/
