name: Shellcheck Validation

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - test
    - feature/*
    - feat/*
    paths-ignore:
    - "**/*.md"

jobs:
  script-validation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        submodules: recursive

    - name: Install test dependencies
      run: sudo apt-get update && sudo apt-get install --no-install-recommends -y git-crypt

    - name: Set up mise
      uses: jdx/mise-action@v4.3.0

    - name: Run tests
      run: mise run test

  shellcheck:
    needs: script-validation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Validate with shellcheck
      uses: ludeeus/action-shellcheck@master
      with:
        scandir: functions/
      env:
        SHELLCHECK_OPTS: -e SC1091
