name: Shellcheck Validation

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - feature/*
    - feat/*
    paths-ignore:
    - "**/*.md"

jobs:
  script-validation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up mise
      uses: jdx/mise-action@v3

    - name: Run tests
      run: mise run test

  shellcheck:
    needs: script-validation
    uses: kpatryk/workflows/.github/workflows/shellcheck.yml@v0.2.1
    with:
      os: ubuntu-latest
      scandir: functions/
