name: Test script

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*
      - dependabot/*
    paths-ignore:
      - "**/*.md"

jobs:
  test:
    name: Test shell scripts
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate with shellcheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: "functions/"
